import os

import psycopg2


def get_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing required env var: {name}")
    return value


def main() -> None:
    host = get_env("DB_HOST")
    port = int(get_env("DB_PORT"))
    name = get_env("DB_NAME")
    user = get_env("DB_USER")
    password = get_env("DB_PASSWORD")

    conn = psycopg2.connect(
        host=host,
        port=port,
        dbname=name,
        user=user,
        password=password,
    )
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'test';
                """
            )
            exists = cur.fetchone() is not None

            if not exists:
                cur.execute(
                    """
                    CREATE TABLE public."test" (
                      "Test #" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      "Created at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      "Created by" text
                    );
                    """
                )
        conn.commit()
    finally:
        conn.close()

    print("Table already exists" if exists else "Table created successfully")


if __name__ == "__main__":
    main()
