// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const pooledUrl = env("DATABASE_URL");
const directUrl = process.env.DATABASE_URL_DIRECT ?? process.env.DIRECT_URL ?? pooledUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl,
  },
});
