// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig } from "prisma/config";

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

function loadDotEnvFile(filePath: string): void {
  if (!fs.existsSync(filePath)) return;
  const content = fs.readFileSync(filePath, "utf8");
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eqIndex = line.indexOf("=");
    if (eqIndex <= 0) continue;
    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();
    if (!key || key in process.env) continue;
    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

const here = path.dirname(fileURLToPath(import.meta.url));
loadDotEnvFile(path.join(here, ".env.local"));
loadDotEnvFile(path.join(here, ".env"));

const pooledUrl = process.env.DATABASE_URL;

function inferDirectUrlFromPooledUrl(urlString: string): string {
  try {
    const url = new URL(urlString);
    if (url.hostname.includes("-pooler")) {
      url.hostname = url.hostname.replace(/-pooler(?=\\.|$)/, "");
    }
    return url.toString();
  } catch {
    return urlString;
  }
}

const directUrl =
  process.env.DATABASE_URL_DIRECT ??
  process.env.DIRECT_URL ??
  (pooledUrl ? inferDirectUrlFromPooledUrl(pooledUrl) : undefined);

const prismaUrl = directUrl ?? pooledUrl;
if (!prismaUrl) {
  throw new Error("DATABASE_URL is not set (set DATABASE_URL or DATABASE_URL_DIRECT)");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm -C packages/db run seed",
  },
  datasource: {
    url: prismaUrl,
  },
});
